// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKfEptucRfGZunH7YpovwGfkYxeIc4KJQ',
    appId: '1:458781804553:web:cf3c1bce71ad532f1450d8',
    messagingSenderId: '458781804553',
    projectId: 'aplicativoflutter-9fbd5',
    authDomain: 'aplicativoflutter-9fbd5.firebaseapp.com',
    databaseURL: 'https://aplicativoflutter-9fbd5-default-rtdb.firebaseio.com',
    storageBucket: 'aplicativoflutter-9fbd5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvtU8t1KKq_Lrn2AKgr_E05eKqqTEuc78',
    appId: '1:458781804553:android:c1028b54c81ccc7f1450d8',
    messagingSenderId: '458781804553',
    projectId: 'aplicativoflutter-9fbd5',
    databaseURL: 'https://aplicativoflutter-9fbd5-default-rtdb.firebaseio.com',
    storageBucket: 'aplicativoflutter-9fbd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj8Esg9HeggpB1VRQD0ubFfvV3hZSi_xc',
    appId: '1:458781804553:ios:fdbb22f27052b04a1450d8',
    messagingSenderId: '458781804553',
    projectId: 'aplicativoflutter-9fbd5',
    databaseURL: 'https://aplicativoflutter-9fbd5-default-rtdb.firebaseio.com',
    storageBucket: 'aplicativoflutter-9fbd5.appspot.com',
    iosBundleId: 'com.example.graeffeng',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj8Esg9HeggpB1VRQD0ubFfvV3hZSi_xc',
    appId: '1:458781804553:ios:4e50c4069d16b6f81450d8',
    messagingSenderId: '458781804553',
    projectId: 'aplicativoflutter-9fbd5',
    databaseURL: 'https://aplicativoflutter-9fbd5-default-rtdb.firebaseio.com',
    storageBucket: 'aplicativoflutter-9fbd5.appspot.com',
    iosBundleId: 'com.example.graeffeng.RunnerTests',
  );
}
